import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import App from '../App.vue'
import ItemEditor from './ItemEditor.vue'
import ReviewPanel from './ReviewPanel.vue'
import DuplicateComparison from './DuplicateComparison.vue'
import * as vaultDomain from '../domain/vault'
import Tooltip from './Tooltip.vue'
import { setLanguage, setTheme } from '../preferences'
import { type CandidateRequest, type IssueRequest, type ValidationBundle, type VaultExport } from '../domain/vault'
let wrapper: VueWrapper
beforeEach(() => {
  vi.spyOn(window, 'confirm').mockReturnValue(true)
  HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', '') }
})
afterEach(() => { wrapper?.unmount(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
async function open(source: VaultExport, replace = false) {
  const encoded = new TextEncoder().encode(JSON.stringify(source))
  const bytes = new ArrayBuffer(encoded.length); new Uint8Array(bytes).set(encoded)
  class Reader {
    result = bytes
    onload: (() => void) | null = null
    onerror: (() => void) | null = null
    readAsArrayBuffer() { queueMicrotask(() => this.onload?.()) }
    abort() {}
  }
  vi.stubGlobal('FileReader', Reader)
  if (!replace) wrapper = mount(App, { attachTo: document.body })
  const input = wrapper.get('input[type=file]')
  Object.defineProperty(input.element, 'files', { configurable: true, value: [new File([''], 'synthetic.json')] })
  await input.trigger('change'); await flushPromises()
  await wrapper.get('dialog .primary').trigger('click')
}
const source: VaultExport = { encrypted: false, items: [
  { id: 'same', type: 1, name: 'Alpha', login: { password: 'synthetic-password' } },
  { id: 'same', type: 1, name: 'Zebra', login: { username: 'synthetic-user', uris: [{ uri: 'https://example.test' }] } },
] }
describe('named export review', () => {
  it('resets filename drafts on replacement and close and never revives dismissed names', async () => {
    await open(source); await wrapper.get('.toolbar-actions .primary').trigger('click')
    await wrapper.get('#export-filename').setValue('private-draft-name')
    await open({ items: [{ type: 2, name: 'Replacement' }] }, true)
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    expect((wrapper.get('#export-filename').element as HTMLInputElement).value).toBe('synthetic-edited.json')
    await wrapper.get('dialog footer .button').trigger('click')
    await wrapper.findAll('.sidebar-footer > button').at(-1)!.trigger('click')
    expect(wrapper.find('#export-filename').exists()).toBe(false)
    await open(source, true); await wrapper.get('.toolbar-actions .primary').trigger('click')
    expect((wrapper.get('#export-filename').element as HTMLInputElement).value).toBe('synthetic-edited.json')
  })
  it('requests the displayed filename without changing contents and preserves original bytes', async () => {
    const blobs: Blob[] = [], names: string[] = []
    const NativeReader = FileReader
    vi.stubGlobal('URL', class extends URL { static createObjectURL(blob: Blob) { blobs.push(blob); return 'blob:synthetic' } static revokeObjectURL() {} })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(function (this: HTMLAnchorElement) { names.push(this.download) })
    await open(source)
    const read = (blob: Blob) => new Promise<string>(resolve => { const reader = new NativeReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsText(blob) })
    for (const name of ['report', 'تقرير.JSON']) {
      await wrapper.get('.toolbar-actions .primary').trigger('click')
      await wrapper.get('#export-filename').setValue(name)
      expect(wrapper.get('#export-filename').attributes('aria-describedby')).toContain('export-filename-help')
      const displayed = wrapper.get('.export-filename-preview').text()
      await wrapper.get('dialog .primary').trigger('click')
      expect(displayed).toContain(names.at(-1))
      expect(JSON.parse(await read(blobs.at(-1)!))).toEqual(source)
    }
    await wrapper.get('.original-copy').trigger('click')
    expect(names.at(-1)).toBe('original-synthetic.json')
    expect(await read(blobs.at(-1)!)).toBe(JSON.stringify(source))
    expect(wrapper.get('[aria-label="Undo"]').attributes('disabled')).toBeDefined()
  })
  it('retains invalid input, resets on dismiss and blocks drafts without confirmation', async () => {
    await open(source)
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    expect((wrapper.get('#export-filename').element as HTMLInputElement).value).toBe('synthetic-edited.json')
    await wrapper.get('#export-filename').setValue('CON.json')
    expect(wrapper.get('#export-filename').attributes('aria-invalid')).toBe('true')
    expect(wrapper.get('#export-filename-error').text()).not.toBe('')
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeDefined()
    await wrapper.get('dialog footer .button').trigger('click')
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    expect((wrapper.get('#export-filename').element as HTMLInputElement).value).toBe('synthetic-edited.json')
    await wrapper.get('dialog footer .button').trigger('click')
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Keep draft')
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    expect(wrapper.find('dialog').exists()).toBe(false)
    expect(window.confirm).not.toHaveBeenCalled()
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep draft')
  })
  it('retains the full-export dirty baseline after failed download and blocks folder drafts', async () => {
    await open(source)
    await wrapper.get('.star-button').trigger('click')
    vi.stubGlobal('URL', class extends URL { static createObjectURL(): string { throw new Error('synthetic failure') } })
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    await wrapper.get('dialog .primary').trigger('click')
    expect(wrapper.find('.vault-file .unsaved').exists()).toBe(true)
    expect(wrapper.find('dialog').exists()).toBe(true)
    await wrapper.get('dialog footer .button').trigger('click')
    await wrapper.get('[aria-label="Create folder"]').trigger('click')
    await wrapper.get('#folder-form input').setValue('Keep folder draft')
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 's', ctrlKey: true, bubbles: true, cancelable: true }))
    await flushPromises()
    expect(wrapper.find('#export-filename').exists()).toBe(false)
    expect((wrapper.get('#folder-form input').element as HTMLInputElement).value).toBe('Keep folder draft')
  })
})
describe('selected export review', () => {
  it('rejects captured folder revision and invalid selection before touching a replacement draft', async () => {
    const document: VaultExport = { folders: [{ id: 'f', name: 'Folder' }], items: [{ type: 2, name: 'Synthetic', folderId: 'f' }] }
    await open(document); await wrapper.get('.review-nav').trigger('click')
    const revision = wrapper.getComponent(ReviewPanel).props('validation').revision
    const state = wrapper.vm.$ as unknown as { setupState: { requestExport: (scope: unknown, revision?: number) => void } }
    const request = state.setupState.requestExport
    await open(document, true); await wrapper.get('.name-cell button').trigger('click'); await wrapper.get('.editor-section input').setValue('Replacement draft')
    const prompts = vi.mocked(window.confirm).mock.calls.length
    request({ kind: 'folder', path: 'Folder', folderIndex: 0 }, revision)
    request({ kind: 'selected', indexes: [-1] }); await flushPromises()
    expect(wrapper.find('#export-filename').exists()).toBe(false)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Replacement draft')
    expect(window.confirm).toHaveBeenCalledTimes(prompts)
  })
  it.each(['undo', 'redo', 'delete', 'replace'] as const)('invalidates selected and folder reviews on %s rather than adopting shifted members', async transition => {
    for (const scope of ['selected', 'folder']) {
      if (scope === 'folder') wrapper.unmount()
      await open({ folders: [{ id: 'f', name: 'Folder' }], items: [{ type: 2, name: 'First', folderId: 'f' }, { type: 2, name: 'Second', folderId: 'f' }] })
      await wrapper.get('.star-button').trigger('click')
      if (transition === 'redo') await wrapper.get('[aria-label="Undo"]').trigger('click')
      await wrapper.get('tbody input[type=checkbox]').setValue(true)
      await wrapper.get(scope === 'selected' ? '.export-selected' : '.export-folder').trigger('click')
      if (transition === 'replace') {
        await open({ items: [{ type: 2, name: 'Replacement' }] }, true)
        expect(wrapper.find('#export-filename').exists()).toBe(false)
      } else {
        await wrapper.get(transition === 'delete' ? '[aria-label="Delete selected items"]' : `[aria-label="${transition === 'undo' ? 'Undo' : 'Redo'}"]`).trigger('click')
        expect(wrapper.get('dialog .primary').attributes('disabled')).toBeDefined()
        expect(wrapper.get('dialog [role=alert]').text()).toContain('no longer current')
      }
    }
  })
  it('exports selections across pages in source order without resetting the dirty baseline or history', async () => {
    const NativeReader = FileReader, blobs: Blob[] = []
    vi.stubGlobal('URL', class extends URL { static createObjectURL(blob: Blob) { blobs.push(blob); return 'blob:synthetic' } static revokeObjectURL() {} })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    const doc: VaultExport = { opaque: { retain: true }, items: Array.from({ length: 80 }, (_, index) => ({ id: 'same', type: 2, name: `Synthetic ${index}` })) }
    await open(doc)
    expect(wrapper.find('.export-selected').exists()).toBe(false)
    await wrapper.get('.star-button').trigger('click')
    await wrapper.get('[aria-label="Sort by"]').setValue('name'); await wrapper.get('[aria-label="Sort direction"]').setValue('desc')
    await wrapper.get('tbody input[type=checkbox]').setValue(true)
    await wrapper.get('[aria-label="Next page"]').trigger('click'); await wrapper.get('tbody input[type=checkbox]').setValue(true)
    const changes = wrapper.get('.changes-button').text()
    await wrapper.get('.export-selected').trigger('click')
    expect(wrapper.get('.export-scope').text()).toContain('2 items')
    expect((wrapper.get('#export-filename').element as HTMLInputElement).value).toBe('synthetic-selected.json')
    await wrapper.get('dialog .primary').trigger('click')
    const read = new NativeReader(); const content = await new Promise<string>(resolve => { read.onload = () => resolve(String(read.result)); read.readAsText(blobs[0]!) })
    const result = JSON.parse(content)
    expect(result.items.map((item: { name: string }) => item.name)).toEqual(['Synthetic 4', 'Synthetic 79'])
    expect(result.opaque).toEqual(doc.opaque)
    expect(wrapper.find('.vault-file .unsaved').exists()).toBe(true)
    expect(wrapper.get('.changes-button').text()).toBe(changes)
    expect(wrapper.get('.bulk-toolbar').text()).toContain('2 selected')
    expect(wrapper.get('[aria-label="Undo"]').attributes('disabled')).toBeUndefined()
  })
  it('validates the result, maps compacted issue indexes to source and rejects stale reviews', async () => {
    await open({ items: [{ type: 1, name: 'Excluded error', login: [] as unknown as Record<string, unknown> }, { type: 1, name: 'Retained warning', login: { username: 'synthetic' } }] })
    await wrapper.findAll('tbody input[type=checkbox]')[1]!.setValue(true)
    await wrapper.get('.export-selected').trigger('click')
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeUndefined()
    await wrapper.get('.export-issues .text-button').trigger('click'); await flushPromises()
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(1)
    expect(document.activeElement).toBe(wrapper.get('[data-issue-field="login.password"]').element)
    await wrapper.get('[aria-label="Close item editor"]').trigger('click')
    await wrapper.get('.export-selected').trigger('click')
    await wrapper.findAll('tbody input[type=checkbox]')[0]!.setValue(true)
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeDefined()
    expect(wrapper.get('dialog [role=alert]').text()).toContain('no longer current')
  })
  it('blocks unsafe ownership metadata and preserves cancellation and draft guards', async () => {
    await open({ organizations: { opaque: true }, items: [{ type: 2, name: 'Synthetic' }] })
    await wrapper.get('tbody input[type=checkbox]').setValue(true)
    await wrapper.get('.export-selected').trigger('click')
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeDefined()
    expect(wrapper.get('dialog .issue-row.error').text()).toContain('safely narrow')
    await wrapper.get('dialog footer .button').trigger('click')
    expect(wrapper.get('.bulk-toolbar').text()).toContain('1 selected')
    await wrapper.get('.name-cell button').trigger('click'); await wrapper.get('.editor-section input').setValue('Keep draft')
    await wrapper.get('.export-selected').trigger('click')
    expect(wrapper.find('dialog').exists()).toBe(false)
    expect(window.confirm).not.toHaveBeenCalled()
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep draft')
  })
})
describe('duplicate comparison actions', () => {
  it('retains comparison and item drafts after a failed candidate mutation', async () => {
    await open({ items: [0, 1].map(() => ({ type: 1, name: 'Synthetic same', login: { username: 'synthetic', uris: [{ uri: 'https://example.test' }] } })) })
    await wrapper.get('.name-cell button').trigger('click'); await wrapper.get('.review-nav').trigger('click'); await wrapper.get('.compare-group').trigger('click')
    await wrapper.get('.rename-candidate').trigger('click'); await wrapper.get('.comparison-name-input').setValue('Keep comparison draft')
    await wrapper.get('.editor-section input').setValue('Keep item draft')
    const before = wrapper.getComponent(ReviewPanel).props('document')
    vi.spyOn(vaultDomain, 'updateItem').mockImplementation(() => { throw new Error('synthetic mutation failure') })
    await wrapper.get('.comparison-name-form .primary').trigger('click')
    expect(wrapper.getComponent(ReviewPanel).props('document')).toBe(before)
    expect((wrapper.get('.comparison-name-input').element as HTMLInputElement).value).toBe('Keep comparison draft')
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep item draft')
    expect(wrapper.get('.changes-button').text()).toContain('0 changes')
  })
  const duplicates: VaultExport = { opaque: { unchanged: true }, items: [0, 1, 2].map(index => ({ ...(index < 2 ? { id: 'same' } : {}), type: 1, name: 'Duplicate', notes: `Synthetic ${index}`, login: { username: 'synthetic', password: `synthetic-${index}`, uris: [{ uri: 'https://example.test' }, { uri: 'https://other.test' }] } })) }
  it.each(['delete', 'undo', 'redo', 'replace'] as const)('rejects stale candidate callbacks after %s before any draft/destructive prompt', async transition => {
    await open(duplicates)
    await wrapper.get('.star-button').trigger('click')
    if (transition === 'redo') await wrapper.get('[aria-label="Undo"]').trigger('click')
    await wrapper.get('.review-nav').trigger('click'); await wrapper.get('.compare-group').trigger('click')
    const component = wrapper.getComponent(DuplicateComparison)
    const request: CandidateRequest = { group: component.props('request'), index: 0 }
    const remove = component.vm.$.vnode.props!.onDelete as (request: CandidateRequest) => void
    if (transition === 'delete') await wrapper.get('.delete-candidate').trigger('click')
    else if (transition === 'replace') await open(duplicates, true)
    else await wrapper.get(`[aria-label="${transition === 'undo' ? 'Undo' : 'Redo'}"]`).trigger('click')
    await wrapper.get('.vault-nav button').trigger('click'); await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Keep new occupant draft')
    const before = wrapper.getComponent(ItemEditor).props('item'), prompts = vi.mocked(window.confirm).mock.calls.length
    remove(request); await flushPromises()
    expect(wrapper.getComponent(ItemEditor).props('item')).toBe(before)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep new occupant draft')
    expect(window.confirm).toHaveBeenCalledTimes(prompts)
  })
  it('rechecks a candidate after confirmation when undo changes the revision before commit', async () => {
    await open(duplicates); await wrapper.get('.star-button').trigger('click')
    await wrapper.get('.review-nav').trigger('click'); await wrapper.get('.compare-group').trigger('click')
    vi.mocked(window.confirm).mockImplementationOnce(() => {
      // Stress a revision change while the captured prompt is being answered.
      ;(wrapper.get('[aria-label="Undo"]').element as HTMLButtonElement).click()
      return true
    })
    await wrapper.get('.delete-candidate').trigger('click')
    expect(wrapper.getComponent(ReviewPanel).props('document')).toEqual(duplicates)
  })
  it('compares all candidates, renames only one name and deletes exactly one with confirmation/undo', async () => {
    await open(duplicates); await wrapper.get('.review-nav').trigger('click'); await wrapper.get('.compare-group').trigger('click')
    expect(wrapper.findAll('.candidate-name')).toHaveLength(3)
    await wrapper.findAll('.rename-candidate')[1]!.trigger('click')
    await wrapper.get('.comparison-name-input').setValue('Renamed')
    await wrapper.get('.comparison-name-form .primary').trigger('click')
    expect(wrapper.find('.duplicate-comparison').exists()).toBe(false)
    const document = wrapper.getComponent(ReviewPanel).props('document')
    expect(document.items).toEqual(duplicates.items!.map((item, index) => index === 1 ? { ...item, name: 'Renamed' } : item))
    await wrapper.get('.compare-group').trigger('click')
    vi.mocked(window.confirm).mockReturnValueOnce(false)
    await wrapper.findAll('.delete-candidate')[1]!.trigger('click')
    expect(wrapper.getComponent(ReviewPanel).props('document')).toBe(document)
    await wrapper.findAll('.delete-candidate')[1]!.trigger('click')
    expect(window.confirm).toHaveBeenLastCalledWith(expect.stringContaining('Renamed'))
    expect(wrapper.getComponent(ReviewPanel).props('document').items).toEqual([document.items![0], document.items![2]])
    await wrapper.get('[aria-label="Undo"]').trigger('click')
    expect(wrapper.getComponent(ReviewPanel).props('document')).toEqual(document)
    await wrapper.get('[aria-label="Undo"]').trigger('click')
    expect(wrapper.getComponent(ReviewPanel).props('document')).toEqual(duplicates)
  })
  it('rejects nontext rename payloads without a mutation and removes groups with fewer than two candidates', async () => {
    await open({ items: duplicates.items!.slice(0, 2) }); await wrapper.get('.review-nav').trigger('click'); await wrapper.get('.compare-group').trigger('click')
    await wrapper.get('.rename-candidate').trigger('click')
    const component = wrapper.getComponent(DuplicateComparison), before = wrapper.getComponent(ReviewPanel).props('document')
    component.vm.$emit('rename', { group: component.props('request'), index: 0, name: 42 }); await flushPromises()
    expect(wrapper.getComponent(ReviewPanel).props('document')).toBe(before)
    expect(wrapper.get('.changes-button').text()).toContain('0 changes')
    await wrapper.get('.delete-candidate').trigger('click')
    expect(wrapper.find('.compare-group').exists()).toBe(false)
    await wrapper.get('[aria-label="Undo"]').trigger('click')
    expect(wrapper.find('.compare-group').exists()).toBe(true)
  })
  it('ignores exact group/rule in App memory, survives remount/preferences and resets on document change', async () => {
    await open(duplicates); await wrapper.get('.review-nav').trigger('click')
    expect(wrapper.findAll('.compare-group')).toHaveLength(1)
    const document = wrapper.getComponent(ReviewPanel).props('document'), warnings = wrapper.getComponent(ReviewPanel).props('validation').issues
    await wrapper.get('.compare-group').trigger('click'); await wrapper.get('.ignore-group').trigger('click')
    expect(wrapper.find('.compare-group').exists()).toBe(false)
    expect(wrapper.getComponent(ReviewPanel).props('document')).toBe(document)
    expect(wrapper.getComponent(ReviewPanel).props('validation').issues).toEqual(warnings)
    expect(wrapper.get('.changes-button').text()).toContain('0 changes')
    await wrapper.get('.vault-nav button').trigger('click'); await wrapper.get('.review-nav').trigger('click')
    setTheme('dark'); await flushPromises()
    expect(wrapper.find('.compare-group').exists()).toBe(false)
    await wrapper.get('.review-filter select').setValue('name')
    expect(wrapper.find('.compare-group').exists()).toBe(true)
    await wrapper.get('.review-filter select').setValue('credential')
    setLanguage('ar'); await flushPromises()
    expect(wrapper.find('.compare-group').exists()).toBe(false)
    setLanguage('en'); await flushPromises()
    await wrapper.get('.restore-groups').trigger('click')
    expect(wrapper.find('.compare-group').exists()).toBe(true)
    await wrapper.get('.compare-group').trigger('click'); await wrapper.get('.ignore-group').trigger('click')
    await wrapper.get('.vault-nav button').trigger('click'); await wrapper.get('.star-button').trigger('click'); await wrapper.get('.review-nav').trigger('click')
    expect(wrapper.find('.compare-group').exists()).toBe(true)
  })
  it('preserves editor and comparison-name drafts when guards or Back/Escape are declined', async () => {
    await open(duplicates); await wrapper.get('.name-cell button').trigger('click'); await wrapper.get('.editor-section input').setValue('Keep item draft')
    await wrapper.get('.review-nav').trigger('click'); await wrapper.get('.compare-group').trigger('click')
    vi.mocked(window.confirm).mockReturnValue(false)
    await wrapper.get('.rename-candidate').trigger('click')
    expect(wrapper.find('.comparison-name-input').exists()).toBe(false)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep item draft')
    await wrapper.get('.delete-candidate').trigger('click')
    expect(wrapper.getComponent(ReviewPanel).props('document')).toEqual(duplicates)
    vi.mocked(window.confirm).mockReturnValue(true)
    await wrapper.get('.rename-candidate').trigger('click'); await wrapper.get('.comparison-name-input').setValue('Keep comparison draft')
    vi.mocked(window.confirm).mockReturnValue(false)
    await wrapper.get('.comparison-back').trigger('click')
    expect((wrapper.get('.comparison-name-input').element as HTMLInputElement).value).toBe('Keep comparison draft')
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true })); await flushPromises()
    expect(wrapper.find('.duplicate-comparison').exists()).toBe(true)
    vi.mocked(window.confirm).mockReturnValue(true); await wrapper.get('.comparison-back').trigger('click')
    expect(wrapper.find('.duplicate-comparison').exists()).toBe(false)
  })
})
describe('contextual issue navigation', () => {
  it('exports actual and virtual folder branches independently of filters and reviews empty scope', async () => {
    const NativeReader = FileReader, blobs: Blob[] = []
    vi.stubGlobal('URL', class extends URL { static createObjectURL(blob: Blob) { blobs.push(blob); return 'blob:synthetic' } static revokeObjectURL() {} })
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    const source: VaultExport = { folders: [{ id: 'p', name: 'Work' }, { id: 'c', name: 'Work/Child' }, { id: 'e', name: 'Virtual/Empty' }, { id: 'x', name: 'Workshop' }], items: [{ type: 2, folderId: 'p', name: 'Direct' }, { type: 2, folderId: 'c', name: 'Child' }, { type: 2, folderId: 'x', name: 'Outside' }] }
    await open(source); await wrapper.get('.search-wrap input').setValue('Outside')
    await wrapper.get('.folder-entry:has([title="Work"]) .export-folder').trigger('click')
    expect(wrapper.get('.export-scope').text()).toContain('2 items')
    expect((wrapper.get('#export-filename').element as HTMLInputElement).value).toBe('synthetic-folder.json')
    await wrapper.get('dialog .primary').trigger('click')
    const reader = new NativeReader(); const output = await new Promise<string>(resolve => { reader.onload = () => resolve(String(reader.result)); reader.readAsText(blobs[0]!) })
    expect(JSON.parse(output).items).toEqual(source.items!.slice(0, 2))
    expect((wrapper.get('.search-wrap input').element as HTMLInputElement).value).toBe('Outside')
    await wrapper.get('.virtual-folder .export-folder').trigger('click')
    expect(wrapper.get('.export-scope').text()).toContain('0 items')
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeUndefined()
    expect(wrapper.get('dialog').text()).toContain('zero-item')
  })
  it('blocks ambiguous branches/unsafe metadata without affecting selected-export rules or source', async () => {
    await open({ folders: [{ id: 'a', name: 'Work' }, { id: 'b', name: 'Work' }], items: [{ type: 2, name: 'A', folderId: 'a' }] })
    await wrapper.get('.export-folder').trigger('click')
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeDefined()
    expect(wrapper.get('.issue-row.error').text()).toContain('duplicate full paths')
    await wrapper.get('dialog footer .button').trigger('click')
    await wrapper.get('tbody input[type=checkbox]').setValue(true); await wrapper.get('.export-selected').trigger('click')
    expect(wrapper.get('dialog .primary').attributes('disabled')).toBeUndefined()
    await wrapper.get('dialog footer .button').trigger('click')
    await open({ folders: [{ id: 'a', name: 'Work' }], organizations: null, items: [] }, true)
    await wrapper.get('.export-folder').trigger('click')
    expect(wrapper.get('.issue-row.error').text()).toContain('safely narrow')
    expect(wrapper.get('.changes-button').text()).toContain('0 changes')
  })
  it.each(['delete', 'undo', 'redo', 'replace'] as const)('rejects a captured request after %s while retaining a new occupant draft', async transition => {
    await open(source)
    await wrapper.get('.review-nav').trigger('click')
    const review = wrapper.getComponent(ReviewPanel)
    const bundle = review.props('validation') as ValidationBundle
    const request: IssueRequest = { revision: bundle.revision, issue: bundle.issues.find(issue => issue.itemIndex === (transition === 'delete' ? 0 : 1))! }
    const inspect = review.vm.$.vnode.props!.onInspectIssue as (request: IssueRequest) => void
    await wrapper.get('.vault-nav button').trigger('click')
    if (transition === 'delete') {
      await wrapper.get('tbody input[type=checkbox]').setValue(true)
      await wrapper.get('[aria-label="Delete selected items"]').trigger('click')
      expect(wrapper.get('.name-cell button').text()).toContain('Zebra')
    } else if (transition === 'replace') await open({ items: [{ type: 2, name: 'Replacement without ID' }] }, true)
    else {
      await wrapper.get('.star-button').trigger('click')
      await wrapper.get('[aria-label="Undo"]').trigger('click')
      if (transition === 'redo') await wrapper.get('[aria-label="Redo"]').trigger('click')
    }
    await wrapper.get('tbody input[type=checkbox]').setValue(true)
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Do not discard stale draft')
    const before = wrapper.getComponent(ItemEditor).props('item')
    const confirmations = vi.mocked(window.confirm).mock.calls.length
    inspect(request); await flushPromises()
    expect(wrapper.getComponent(ItemEditor).props('item')).toBe(before)
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(0)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Do not discard stale draft')
    expect((wrapper.get('tbody input[type=checkbox]').element as HTMLInputElement).checked).toBe(true)
    expect(window.confirm).toHaveBeenCalledTimes(confirmations)
    expect(wrapper.get('[role="status"]').text()).toContain('no longer available')
  })
  it('preserves page, filters, sort, selection and draft when an off-page warning is cancelled, then accepts it', async () => {
    await open({ items: Array.from({ length: 80 }, (_, index) => ({ id: index % 2 ? 'repeated' : undefined, type: 1, name: `Synthetic ${index}`, login: { username: 'synthetic' } })) })
    await wrapper.get('.filter-button').trigger('click')
    await wrapper.get('#vault-filters label:nth-child(3) select').setValue('__personal')
    await wrapper.get('.search-wrap input').setValue('Synthetic')
    await wrapper.get('[aria-label="Sort by"]').setValue('name')
    await wrapper.get('[aria-label="Sort direction"]').setValue('desc')
    await wrapper.get('[aria-label="Next page"]').trigger('click')
    await wrapper.get('tbody input[type=checkbox]').setValue(true)
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Page two draft')
    const editor = wrapper.getComponent(ItemEditor)
    const index = editor.props('index')
    const page = wrapper.get('.pagination').text()
    vi.mocked(window.confirm).mockReturnValue(false)
    await wrapper.findAll('.warning-indicator')[1]!.trigger('click')
    expect(editor.props('index')).toBe(index)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Page two draft')
    expect(wrapper.get('.pagination').text()).toBe(page)
    expect(wrapper.get('.bulk-toolbar').text()).toContain('1 selected')
    expect((wrapper.get('.search-wrap input').element as HTMLInputElement).value).toBe('Synthetic')
    expect((wrapper.get('[aria-label="Sort direction"]').element as HTMLSelectElement).value).toBe('desc')
    await wrapper.get('.filter-button').trigger('click')
    expect((wrapper.get('#vault-filters label:nth-child(3) select').element as HTMLSelectElement).value).toBe('__personal')
    vi.mocked(window.confirm).mockReturnValue(true)
    await wrapper.findAll('.warning-indicator')[1]!.trigger('click'); await flushPromises()
    expect(wrapper.getComponent(ItemEditor).props('index')).not.toBe(index)
    expect(wrapper.get('.pagination').text()).toBe(page)
    expect(wrapper.get('.bulk-toolbar').text()).toContain('1 selected')
  })
  it('uses exact URI positions and safe ownership, malformed-login and unsupported-item contexts', async () => {
    await open({ items: [{ type: 1, name: 'URI', login: { username: 'synthetic', password: 'synthetic', uris: [{ uri: 'https://valid.test' }, { uri: 42 }] } }, { type: 1, name: 'Malformed', login: [] }, { type: 9, name: 'Unknown' }, { type: 2, name: 'Owned', collectionIds: ['synthetic'] }] } as unknown as VaultExport)
    await wrapper.get('.review-nav').trigger('click')
    const review = wrapper.getComponent(ReviewPanel)
    const bundle = review.props('validation') as ValidationBundle
    for (const [message, selector] of [['validation.uris', '.uri-input:nth-of-type(2) input'], ['validation.login', '.malformed-login'], ['validation.unsupported', '.issue-context h3'], ['validation.organization', '.metadata summary']] as const) {
      const issue = bundle.issues.find(issue => issue.message === message)!
      review.vm.$emit('inspectIssue', { revision: bundle.revision, issue }); await flushPromises()
      const target = message === 'validation.uris' ? wrapper.findAll('.uri-input input')[1]! : wrapper.get(selector)
      expect(document.activeElement).toBe(target.element)
      expect(wrapper.find('.code-input').exists()).toBe(false)
      if (message === 'validation.organization') expect((wrapper.get('.metadata').element as HTMLDetailsElement).open).toBe(true)
    }
    const issue = bundle.issues.find(issue => issue.message === 'validation.noUri')!
    review.vm.$emit('inspectIssue', { revision: bundle.revision, issue }); await flushPromises()
    expect(document.activeElement).toBe(wrapper.get('.add-uri').element)
  })
  it('keeps static action help hoverable and associates it with keyboard controls', async () => {
    vi.useFakeTimers()
    try {
      wrapper = mount(Tooltip, { props: { text: 'Static synthetic action explanation' }, slots: { default: '<button aria-label="Synthetic action">Action</button>' }, attachTo: document.body })
      expect(wrapper.get('button').attributes('aria-describedby')).toBe(wrapper.get('[role="tooltip"]').attributes('id'))
      await wrapper.trigger('mouseenter')
      expect(wrapper.get('[role="tooltip"]').isVisible()).toBe(true)
      await wrapper.trigger('mouseleave'); vi.advanceTimersByTime(50)
      await wrapper.get('[role="tooltip"]').trigger('mouseenter'); vi.advanceTimersByTime(150)
      expect(wrapper.get('[role="tooltip"]').isVisible()).toBe(true)
      window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }))
      await flushPromises()
      expect(wrapper.get('[role="tooltip"]').isVisible()).toBe(false)
    } finally { vi.useRealTimers() }
  })
  it('keeps drafts, selection, privacy and optional fields when preference writes fail', async () => {
    await open(source)
    await wrapper.get('[aria-controls="vault-fields"]').trigger('click')
    await wrapper.get('[data-field="created"]').setValue(true)
    await wrapper.get('tbody input[type=checkbox]').setValue(true)
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Preference draft')
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw Error('blocked') })
    for (const language of ['en', 'ar']) for (const value of ['light', 'dark']) {
      setLanguage(language); setTheme(value); await flushPromises()
      expect(document.documentElement.lang).toBe(language)
      expect(document.documentElement.dataset.theme).toBe(value)
      expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Preference draft')
      expect((wrapper.get('tbody input[type=checkbox]').element as HTMLInputElement).checked).toBe(true)
      expect((wrapper.get('[data-field="created"]').element as HTMLInputElement).checked).toBe(true)
      expect(wrapper.get('.privacy-toggle').attributes('aria-pressed')).toBe('true')
    }
  })
  it('describes disabled actions and consumes tooltip Escape without closing an editor', async () => {
    await open(source)
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Keep tooltip draft')
    const tooltip = wrapper.findAllComponents(Tooltip).find(component => component.find('[aria-label="Undo"]').exists())!
    expect(tooltip).toBeDefined()
    await tooltip.trigger('focusin')
    expect(tooltip.get('[role="tooltip"]').isVisible()).toBe(true)
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }))
    await flushPromises()
    expect(tooltip.get('[role="tooltip"]').isVisible()).toBe(false)
    expect(wrapper.findComponent(ItemEditor).exists()).toBe(true)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep tooltip draft')
    expect(wrapper.get('[aria-label="Undo"]').attributes('disabled')).toBeDefined()
  })
  it('focuses exact source fields across sorted rows and keeps them masked', async () => {
    await open(source)
    await wrapper.get('[aria-label="Sort by"]').setValue('name')
    await wrapper.get('[aria-label="Sort direction"]').setValue('desc')
    await wrapper.get('.warning-indicator').trigger('click'); await flushPromises()
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(1)
    expect(document.activeElement).toBe(wrapper.get('[data-issue-field="login.password"]').element)
    expect(wrapper.find('.review-panel').exists()).toBe(false)
    expect(wrapper.get('[data-issue-field="login.password"]').attributes('readonly')).toBeDefined()
  })
  it('cancels warning navigation without changing any draft or navigation state', async () => {
    await open(source)
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.editor-section input').setValue('Unapplied synthetic draft')
    vi.mocked(window.confirm).mockReturnValue(false)
    await wrapper.findAll('.warning-indicator')[1]!.trigger('click')
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(0)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Unapplied synthetic draft')
    expect(wrapper.find('.review-panel').exists()).toBe(false)
    expect(wrapper.findAll('.name-cell')).toHaveLength(2)
  })
  it('rejects captured warning requests after undo rather than opening a new occupant', async () => {
    await open(source)
    await wrapper.get('.review-nav').trigger('click')
    const review = wrapper.getComponent(ReviewPanel)
    const bundle = review.props('validation') as { revision: number; issues: unknown[] }
    expect(bundle).toBeDefined()
    review.vm.$emit('inspectIssue', { revision: bundle.revision, issue: bundle.issues[0] })
    await flushPromises()
    await wrapper.get('.editor-section input').setValue('Applied synthetic edit')
    await wrapper.get('.editor-footer .primary').trigger('click')
    await wrapper.get('[aria-label="Undo"]').trigger('click')
    review.vm.$emit('inspectIssue', { revision: bundle.revision, issue: bundle.issues[0] })
    await flushPromises()
    expect(wrapper.findComponent(ItemEditor).exists()).toBe(false)
    expect(wrapper.get('[role="status"]').text()).toContain('no longer available')
  })
  it('preserves a same-item draft while focusing another issue and supports off-list export targets', async () => {
    await open(source)
    await wrapper.get('.warning-indicator').trigger('click'); await flushPromises()
    await wrapper.get('.editor-section input').setValue('Keep this draft')
    const editor = wrapper.getComponent(ItemEditor)
    const issue = editor.props('issues')![1]!
    editor.vm.$emit('inspectIssue', { revision: editor.props('revision'), issue })
    await flushPromises()
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Keep this draft')
    expect(window.confirm).not.toHaveBeenCalled()
    expect(document.activeElement).toBe(wrapper.get('.add-uri').element)
    await wrapper.get('.editor-footer button').trigger('click')
    await wrapper.get('.search-wrap input').setValue('Alpha')
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    const exportIssue = wrapper.findAll('.export-issues .text-button').find(button => button.text().includes('2'))!
    await exportIssue.trigger('click'); await flushPromises()
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(1)
    expect(wrapper.findAll('.name-cell')).toHaveLength(1)
    expect(wrapper.find('.export-issues').exists()).toBe(false)
    expect(document.activeElement).toBe(wrapper.get('[data-issue-field="login.password"]').element)
  })
  it('does not close the originating export dialog on a cancelled discard', async () => {
    await open(source)
    await wrapper.get('.name-cell button').trigger('click')
    await wrapper.get('.toolbar-actions .primary').trigger('click')
    const dialog = wrapper.get('dialog').element
    // Inject a concurrent draft to exercise the shared guard even though a native modal is inert.
    await wrapper.get('.editor-section input').setValue('Concurrent synthetic draft')
    const target = wrapper.findAll('.export-issues .text-button').find(button => button.text().includes('2'))!
    vi.mocked(window.confirm).mockReturnValue(false)
    await target.trigger('click')
    expect(wrapper.get('dialog').element).toBe(dialog)
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(0)
    expect((wrapper.get('.editor-section input').element as HTMLInputElement).value).toBe('Concurrent synthetic draft')
    vi.mocked(window.confirm).mockReturnValue(true)
    await target.trigger('click'); await flushPromises()
    expect(wrapper.find('.export-issues').exists()).toBe(false)
    expect(wrapper.getComponent(ItemEditor).props('index')).toBe(1)
    expect(document.activeElement).toBe(wrapper.get('[data-issue-field="login.password"]').element)
  })
})
